pull_request:
  comment:
    - azure_pipeline:
        allow_list:
          - "wyunchi-ms.azure-powershell - powershell-core"
        result_path: "/PipelineResult/PipelineResult.json"
      group_by_keys:
        - "Module"
        - "PhaseName"
        - "Platform"
      template_path: "templates/comment1.handlebars"
      comment_title: "PowerShell-Core"
      init_comment: "Validation for PowerShell Core Starts. Thanks for your contribution!"
    - azure_pipeline:
        allow_list:
          - "wyunchi-ms.azure-powershell - windows-powershell"
        result_path: "/PipelineResult/PipelineResult.json"
      group_by_keys:
        - "Module"
        - "PhaseName"
        - "Platform"
      template_path: "templates/comment1.handlebars"
      comment_title: "Windows-PowerShell"
      init_comment: "Validation for Windows PowerShell Starts. Thanks for your contribution!"
    - azure_pipeline:
        allow_list:
          - "wyunchi-ms.azure-powershell - powershell-core"
          - "wyunchi-ms.azure-powershell - windows-powershell"
        result_path: "/PipelineResult/PipelineResult.json"
      group_by_keys:
        - "PhaseName"
        - "Module"
        - "Platform"
      template_path: "templates/comment2.handlebars"
      comment_title: "comment2"
      init_comment: "Validation for PowerShell Core and Windows PowerShell Starts. Thanks for your contribution!"
